spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/mybatis_plus?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: a123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource #com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      read-only: false
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
#  type-aliases-package: com.mybatisplus.member.mapper